[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "balancerdata"
version = "0.0.1"
authors = [
  { name="ikerg", email="iker.gabirondo@alumni.mondragon.edu" },
]
description = "Creacion de la libreria para balancear datos"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/ikergabirondo/Balance_library"
"Bug Tracker" = "https://github.com/ikergabirondo/Balance_library/issues"