[project]
name = "biorepo"
version = "0.1.2"
description = ""
authors = [
    {name = "dwpeng", email = "dwpeng1122@foxmail.com"},
]
dependencies = [
    "httpx>=0.25.0",
    "pydantic[email]>=2.4.2",
    "rich>=13.6.0",
    "gitpython>=3.1.40",
    "tomlkit>=0.12.2",
    "chardet>=5.2.0",
    "typer>=0.9.0",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
biorepo = "biorepo.cli.__main__:main"

[tool.pdm.dev-dependencies]
dev = [
    "isort>=5.12.0",
    "ruff>=0.1.4",
]
