[project]
name = "physics-gabri432"
version = "0.2.1"
authors = [
  { name="Gabriele Gatti", email="gabrielegatti432@gmail.com" },
]
maintainers = [
  { name="Gabriele Gatti", email="gabrielegatti432@gmail.com" },
]
description = "A package containing Physics formulas and constants for various calculations."
readme = "README.md"
requires-python = ">=3.12"
license = {text = "MIT license"}
keywords = ['physics', 'library', 'lib', 'relativity', 'thermodynamics', 'classical', 'gravity', 'electromagnetism', 'fluids']
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.12",
    "Intended Audience :: Education",
    "Topic :: Scientific/Engineering :: Physics"
]

[project.urls]
"Github" = "https://github.com/Gabri432/python-physics"
"Github Issues" = "https://github.com/Gabri432/python-physics/issues"