[project]
name = "tactigon_speech"
version = "4.0.1"
authors = [
  { name="Next Industries s.r.l", email="info@nextind.eu" },
]
description = "Tactigon Gear speech to transcribe text into commands"
readme = {file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.8"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "tgear-sdk>=4.1.0",
    "deepspeech-tflite==0.9.3",
    "PyAudio==0.2.13",
    "webrtcvad==2.0.10"
]

[project.urls]
"Homepage" = "https://nextind.eu"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"