[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "skanym-gui"
version = "0.0.2"
description = "gui extension for skanym using GeeXLab engine"
readme = "README.md"
requires-python = "==3.10.*"
license = {file = "LICENSE.txt"} 
authors = [
    {name = "Dimitri Kohler", email = "dimitri.kohler@he-arc.ch"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development",
    "Programming Language :: Python :: 3.10",
]

[project.urls]
Repository  = "https://gitlab-etu.ing.he-arc.ch/isc/general/motion-machine/skanym-package/skanym-gui"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.glsl", "*.xml", "*.jpg"]



