[tool.poetry]
name = "forta-toolkit"
version = "0.1.20"
description = "Tools to help with the common problems of Forta bot development"
authors = ["apehex <apehex@protonmail.com>"]
readme = ".github/README.md"

[tool.poetry.dependencies]
python = ">=3.9, <4"
forta_agent = ">=0.1.23"
web3 = ">=5"

[tool.poetry.group.dev.dependencies]
pytest = ">=7"
pyarrow = ">=13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
