[project]
name = "ehdg_pupil_detector"
version = "1.0.3"
authors = [
  { name="Zaw Lin Tun", email="zawlintun1511@gmail.com" },
]
description = "Python Library for Pupil Detector of Eye Health Diagnostic Group"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/ZawLinTun16925410/ehdg_pupil_detector"
"Bug Tracker" = "https://github.com/ZawLinTun16925410/ehdg_pupil_detector/issues"

[build-system]
requires = ["setuptools>=61.0", "opencv-python>=4.8.1.78", "scipy>=1.11.3", "numpy>=1.26.1"]
build-backend = "setuptools.build_meta"

[repository.pypi]
username = "__token__"
password = "pypi-AgEIcHlwaS5vcmcCJDA2Yjc5MGYyLTE0MmEtNGIzMy04NWJmLTFhNGE1M2U5ZjQxMQACKlszLCJhNjg4MTk5My1jOGVlLTQ2NjUtYTU3MC1mMGY0ZjgxOTRiZDciXQAABiCD3LNAg3Wn2UQsvil-nVGBwE8ZXDSsnL7Nn1emza4rqA"