[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "chatgpt-klient"
version = "0.2.6"
dependencies = [
    "openai",
    "logutils-serpucga",
    "requests",
    "rich",
    "tiktoken"
]
