[tool.poetry]
name = "agl-model-zoo"
version = "0.1.5"
description = ""
authors = ["Thomas J. Lux"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
albumentations = "^1.3.1"
opencv-python = "^4.8.1.78"
icecream = "^2.1.3"
pandas = "^2.1.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
