[project]
name = "django-cookie_consent_gutsh"
version = "1.1.2"
authors = [
    { name="Artem Barskii", email="artemiy.barskiy@gmail.com" },
]
description = "Cookie consent component for any Django web-site"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Framework :: Django :: 4.0",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]

[project.urls]
"Homepage" = "https://github.com/gutsh/django-cookie-consent"

[build-system]
requires = ['setuptools>=40.8.0']
build-backend = 'setuptools.build_meta'
