[tool.poetry]
name = "minder-downloader"
version = "0.1.17"
description = "The minder-downloader module provides a simple interface for downloading datasets and uploading reports using the Minder research portal."
authors = ["Dr Eyal Soreq <eyal.soreq@ukdri.ac.uk>"]
readme = "README.md"
packages = [{include = "minder_downloader"}]

[tool.poetry.dependencies]
python = ">3.9"
pandas = ">2.0"
numpy = ">1.24"
pyyaml = ">6.0"
tqdm = '>4.65.0'
requests = ">2.28.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
