[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "lod_unit"
version = "0.1.0"
description = "A simple python library with an astropy unit for Î»/D"
authors = [
    {name = "Corey Spohn", email = "corey.a.spohn@nasa.gov"}
]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Astronomy"
]

[project.urls]
Home = "https://github.com/CoreySpohn/lod_unit"
Source = "https://github.com/CoreySpohn/lod_unit"
Tracker = "https://github.com/CoreySpohn/lod_unit/issues"
