[tool.poetry]
name = "vdd"
version = "1.1.1"
description = "Tools for Value-Driven Design"
authors = ["Alex Corrie <ajccode@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7.1,<3.11"
platformdirs = ">=2.6.2"
pygsheets = "^2.0.5"
pandas = ">=1.3.5"
numpy = ">=1.21.1"
xlrd = "^2.0"
pytz = ">=2022.6"
openpyxl = "^3.0.10"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.2"
pytest-mock = "^3.8.2"
coverage = "^7"
ddt = "^1.6.0"
pytest-cov = "^4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
