[tool.poetry]
name = "safelayer"
version = "1.0.2"
description = ""
authors = ["yujonglee <yujonglee@repllabs.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
