[tool.poetry]
name = "money_bags"
version = "0.3.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "3.9.18"

[tool.poetry.dev-dependencies]
hypothesis = "^6.88.1"
pytest = "^5.2"
black = "^23.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
