[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.bandit]
exclude_dirs = ["tests", "features"]

[tool.poetry]
name = "profitpulse"
version = "1.3.15"
description = "Manage your personal finances"
authors = ["Luís Miranda <luistm@gmail.com>"]
maintainers = ["Luís Miranda <luistm@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/luistm/profitpulse"


[[tool.poetry.packages]]
include = "profitpulse"
from = "src"

[tool.mypy]
ignore_missing_imports = true

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.black]
max-line-length = 120
target-version = ["py310","py311", "py312"]

[tool.poetry.scripts]
profitpulse = "profitpulse.ui.typercli.main:app"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.103.2"
pendulum = "3.0.0b1"
rich = "^13.6.0"
toml = "^0.10.2"
turbofan = "^0.0.2"
typer = "^0.9.0"

[tool.pytest.ini_options]
markers = ["integration: tags a test as integration tests"]

[tool.poetry.dev-dependencies.bandit]
extras = ["toml"]
version = "^1.7.5"

[tool.poetry.group.dev.dependencies]
behave = "^1.2.6"
black = "^23.1.0"
coverage = "^7.2.1"
flake8 = "^6.0.0"
isort = "^5.12.0"
mypy = "^1.0.1"
nox = "^2023.4.22"
pre-commit = "^3.1.1"
pytest = "^7.2.1"
pytest-random-order = "^1.1.0"
pytest-xdist = "^3.2.0"
types-python-dateutil = "^2.8.19.9"
types-tabulate = "^0.9.0.1"
types-toml = "^0.10.8.6"
