[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "formal-sdk"
version = "1.0.29"
authors = [
  { name="Formal", email="hello@joinformal.com" },
]
description = "Formal SDK"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  'requests >= 2.26.0',
]

# [tool.setuptools.packages.find]
# where = ["src"]

[project.urls]
"Homepage" = "https://github.com/formalco"
