[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jaysun"
license = { text = "MIT" }
version = "0.1.2"
authors = [
    { name = "jaysun", email = "jaysun1015@outlook.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["PyYAML==6.0", "requests==2.30.0", "setuptools==67.3.3"]

[project.urls]
"Homepage" = "https://github.com/Sun-Wen-Jie/jaysun-plugin"
"Bug Tracker" = "https://github.com/Sun-Wen-Jie/jaysun-plugin/issues"




